spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 642759704994-lij6ad4pejlo6n8hc7mvb8jd3hk7bst2.apps.googleusercontent.com
            clientSecret: WpCmKS36j1youaEZq3LRdPZL
          facebook:
            clientId: 343504280290673
            clientSecret: 3bb94d8162f948f0e4fa61fa7f1bd9b7